version: "3"
services:
  redis:
    image: redis
    volumes:
      - db-data:/data
  web:
    depends_on:
      - redis
    image: olivia/userapi:latest
    ports:
      - "5000:3000"
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
volumes:
  db-data: