apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-bootcamp
  labels:
    app: kubernetes-bootcamp
spec:
  replicas: 3  # TO COMPLETE #2: Set the desired number of replicas (e.g., 3 for three replicas)
  selector:
    matchLabels:
      app: kubernetes-bootcamp
  template:
    metadata:
      labels:
        app: kubernetes-bootcamp
    spec:
      containers:
      - name: kubernetes-bootcamp
        image: gcr.io/google-samples/kubernetes-bootcamp:v1  # TO COMPLETE #1: Set the Docker image you want to use
        ports:
        - containerPort: 8080  # Define the port your application listens on
