apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp-service
spec:
  type: NodePort
  selector:
    app: kubernetes-bootcamp  # TO COMPLETE #1: Set the label selector to match your Deployment labels
  ports:
    - port: 8080  # TO COMPLETE #2: Set the port number you want to expose
